export const EventsActionTypes = {
  EVENTS: 'EVENTS',
  EVENTS_LOADING: 'EVENTS_LOADING',
  EVENTS_ERROR: 'EVENTS_ERROR',
  MARKED_DATES: 'MARKED_DATES',
  UPDATE_SINGLE_EVENT: 'UPDATE_SINGLE_EVENT',
  ADD_NEW_EVENT: 'ADD_NEW_EVENT',
  UPDATE_EVENT: 'UPDATE_EVENT',
  DELETE_EVENT: 'DELETE_EVENT',
};
